### ISSUE TITLE
Selenium Webdriver Error

### ISSUE THREAD

**Issue by krissasantos** [learn-co-curriculum/fe-code-along-4#10]
Hello! Every time I run my code, I get errors, specifically "Selenium Webdriver Error. Unable to establish stable connection with Firefox in 60 seconds."

I've never encountered an error like this before.

I updated my gems to make sure it matches with the latest Firefox version I installed. (Firefox 48).
and installed the latest Selenium Driver gem but I still get the same errors. 

I tried running my code first then the code found in the solution but it still brings up the same error.

**Comment by jmburges** [comment]
Thanks for the catch! we fixed the issue
