### ISSUE TITLE
Install Selenium Server Standalone

### ISSUE THREAD

**Issue by hellosylvee** [learn-co-curriculum/fe-code-along-4#15]
I have a problem in FE-Code-Along-IV exercise where I receive this message when I want to push my work into master: 

```
// ♥ learn                                                                                                                                       
Please install Selenium Server Standalone                                                                                                        
[17:01:53] (master) fe-code-along-4-web-031317
```

Do I need to install Selenium Server Standalone to complete this exercise?

**Comment by jsears4585** [comment]
Same issue on Mac with Mozilla installed.

**Comment by IAmAGraham** [comment]
I'm having the same issue.

**Comment by bmcilhenny** [comment]
Anything ever come of this issue?

**Comment by aturkewi** [comment]
cc @jmburges i think the tests need to be `rm`ed

**Comment by jmburges** [comment]
Thanks for the catch! we fixed the issue
