### ISSUE TITLE
Getting "Install Selenium Server Standalone" when running test.

### ISSUE THREAD

**Issue by kenneth-jiang** [learn-co-curriculum/fe-code-along-4#16]
Hello,

I've been getting the message "Please Install Selenium Server Standalone" whenever I run test for this lesson. I have the green onion gem installed. I also googled ways to get the selenium server installed and set up and did so though I am not sure I did it correctly because it still doesn't recognize that it's installed. It seems other students have had problems with this before too but I don't see a solution.

Does anyone have a solution for this? Thank you!

**Comment by jmburges** [comment]
Thanks for the catch! we fixed the issue
