### ISSUE TITLE
tests don't seem to work

### ISSUE THREAD

**Issue by johneckert** [learn-co-curriculum/fe-code-along-4#19]
Tests appear to be broken.  Getting the tests to run required an old version of Firefox (v46).  The old version of Firefox enables tests to run but they do not past even with code copied directly from solution branch.

-------

I just re-ran the tests on a slightly older external monitor: 2 of the 5 passed and all of the tolerance scores improved slightly.

**Comment by jmburges** [comment]
Thanks for the catch! we fixed the issue
