### ISSUE TITLE
Running the learn command

### ISSUE THREAD

**Issue by Brahimndaw** [learn-co-curriculum/fe-code-along-4#5]
The directory has no specs in it and therefore can pass the local test run

**Comment by AnnJohn** [comment]
hi in the canonical version there are specs, but in this version which is deployed to your batch- https://github.com/learn-co-students/fe-code-along-4-001-prework-web - there shouldn't be any specs and no line that says to run tests.

could you let us know if this is the case.

**Comment by jongrover** [comment]
resolved
