### ISSUE TITLE
README says install Firefox to run Learn tests, but there are no tests

### ISSUE THREAD

**Issue by rhoprhh** [learn-co-curriculum/fe-code-along-4#6]
The only text on the lab's page is:
"After you finish, make sure you install Firefox if you haven't already as it is required for the screenshot tests to run. Then, type learn command from Terminal to run local tests."

Then running learn in my terminal returns:
[13:51:33](master) fe-code-along-4-web-0416
// ♥ learn
This directory doesn't appear to have any specs in it.

The lab requires local tests to pass, but there are no local tests.
There is no .specs folder or files in the lab.
There are also no students who have completed this lab according to the website.

**Comment by AnnJohn** [comment]
hi in the canonical version there are specs, but in this version which is deployed to your batch- https://github.com/learn-co-students/fe-code-along-4-001-prework-web - there shouldn't be any specs and no line that says to run tests. 

could you let us know if this is the case.

**Comment by rhoprhh** [comment]
This is what I see when I try and do the lab.
At the bottom of the page are instructions to run tests and to complete the
lab I need to pass local tests.
That version you linked will not complete this lab without tests.

[image: Inline image 1]

**Comment by deniznida** [comment]
@AnnJohn hey, yeah the batch readme does not have the instruction to run learn, but Learn.co is pulling the readme from the canonical repo. Just had another student with the same issue.

**Comment by jongrover** [comment]
I believe this has been resolved
