### ISSUE TITLE
LoadError while running tests

### ISSUE THREAD

**Issue by Dom-Mc** [learn-co-curriculum/fe-code-along-4#8]
I finished up with the project but I'm running into an issue with the test (Firefox is installed and updated as required).  Not sure if it's rvm related but it looked as though a few other people were having similar issues with the lesson.  Here's the call stack I'm receiving:

```
/Users/Dom/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- green_onion (LoadError)
    from /Users/Dom/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/Dom/Development/code/fe-code-along-4-001-prework-web/spec/main_spec.rb:2:in `<top (required)>'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `load'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `<main>'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Dom/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by AnnJohn** [comment]
hi @Dom-Mc sorry for the issue. Because this looks specific to you, can you use the Ask a Question tool and someone from our team will get back to you? 

Thanks!

**Comment by Dom-Mc** [comment]
Hi @AnnJohn,
My apologies for wasting your time if this is on my end.  I updated my gems and I think my initial error was the result of the Psych gem similar to this https://github.com/learn-co-curriculum/first-lab-ruby-learn-cli-osx/issues/4 or at least that was the next issue I ran into.  However I finally got past that to where I could run the tests however all of them are failing.  I even copied index.html and style.css directly from the solution branch to make sure it wasn't my code but they still all fail.

**Comment by AnnJohn** [comment]
hi @Dom-Mc please don't apologize at all! Thank you for updating your gems, and it's strange that the tests are failing. I'll look into this tomorrow in the AM but have you been able to use the Ask a Question feature and get direct help from one of our experts? Thank you again!

**Comment by Dom-Mc** [comment]
I did ask and hadn't received a response, at least not when I last checked.  I'll try again tomorrow however and in the meantime do a little more investigating.

Thank you very much for your time!

**Comment by AnnJohn** [comment]
Of course, no problem! I'll check in with our experts too tomorrow and try to get someone to get in touch with you. Thank you!

**Comment by Dom-Mc** [comment]
Hey @AnnJohn, so I _think_ (could be wrong) there's an issue with the Green Onion gem and it's dependencies: 

**Runtime Dependencies:**
capybara ~> 1.1
fileutils >= 0
oily_png ~> 1.0.2
rainbow >= 0
thor >= 0.14.6

These versions of Capybara and Oily PNG are pretty outdated (2011).  I could try to bring them in but not sure if they would play nicely with rspec at this point.  You obviously know more than I do so just wanted to get your thoughts.

Before I forget, there were actually 2 or 3 older open questions regarding this lab and its testing.  They may have been answered on another forum but wanted to bring it to your attention just in case.

Thanks again!

**Comment by DanielSeehausen** [comment]
Seems to be an issue with green_onion being outdated. It has been throwing error during install re: fileutils (which the gem package is attempting to install as a gem, instead of just requiring as is still the standard in < ruby v2.5.0) Forcing green_onion install with the -f flag will push through the error and allow it to run properly (as fileutils is required correctly in the spec). Updating with a fix in the readme now.
